const express =require('express')
const Router = express.Router()
const Jwt = require('../utils/jwt')
Router.post('/login',(req,res)=>{
  console.log(req.body)
  let {us,ps}=req.body
  let result={err:0,rootList:[],msg:'登录ok',token:null}
  if(us=='wangyi'&&ps=='123'){
    result.name='wangyi'
    result.user='http://img3.imgtn.bdimg.com/it/u=3298005417,2605075504&fm=26&gp=0.jpg'
     result.rootList=[
        {
        title:"首页",
        key:'0',
        path:'/admin/home',
        bread:'首页',
        icon:'bank'
      },
      {
        title:'数据统计',
        key:'1',
        path:'/admin/chart',
        bread:'数据统计',
        icon:'file-search'
      },
      {
        title:'商品管理',
        key:'3',
        path:'/admin/goods',
        icon:'shopping-cart',
        children:[
          {
            title:'商品列表',
            key:'3-0',
            path:'/admin/goods/list',
            bread:'商品管理/商品列表',
            icon:'profile',            
          },
          {
            title:'商品添加',
            key:'3-1',
            path:'/admin/goods/add',
            bread:'商品管理/商品添加',
            icon:'folder-add',
          },
        ]
      }
     ]
     result.token=Jwt.creatToken('wanger',1500)
  }else if(us=='wanger'&&ps=='456'){
    result.name='wanger'
    result.user='https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png'
    result.rootList=[
      {
        title:"首页",
        key:'0',
        path:'/admin/home',
        bread:'首页',
        icon:'bank'
      },
      {
        title:'数据统计',
        key:'1',
        path:'/admin/chart',
        bread:'数据统计',
        icon:'file-search'
      },
      {
        title:'商品管理',
        key:'3',
        path:'/admin/goods',
        icon:'shopping-cart',
        children:[
          {
            title:'商品列表',
            key:'3-0',
            path:'/admin/goods/list',
            bread:'商品管理/商品列表',
            icon:'profile',            
          },
          {
            title:'商品添加',
            key:'3-1',
            path:'/admin/goods/add',
            bread:'商品管理/商品添加',
            icon:'folder-add',
          },
        ]
      },
      {
        title:'会员管理',
        key:'2',
        path:'/admin/vip',
        icon:'user',
        children:[
          {
            title:'会员添加',
            key:'2-0',
            path:'/admin/vip/add',
            bread:'会员管理/会员添加',
            icon:'user-add',
          },
          {
            title:'会员修改',
            key:'2-1',
            path:'/admin/vip/update',
            bread:'会员管理/会员修改',
            icon:'user-delete',
          },
        ]
      },
      {
        title:'分析中心',
        key:'4',
        path:'/admin/user',
        bread:'分析中心',
        icon:'bar-chart'
      }    
    ]
    
    result.token=Jwt.creatToken('wangyi',1500)
  }else{
    result.err=-1
    result.msg='登录失败'
  }
  res.send(result)
})
module.exports=Router